services:
  whisper-server:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    ports:
      - "9090:9090"  # Replace with the actual port your application is running on
    volumes:
      - .:/app  # Mounts the current directory to /app inside the container, adjust if needed
    restart: always  # Ensures the service restarts if it crashes
  rtsp-server-speaker1:
    image: bluenviron/mediamtx:latest
    build:
      context: .
    volumes:
      - /Users/sebastiankravetz/Dev/Projects/AInterpreter_Hackathon/backend/whisper-live/speakerone.yml:/mediamtx.yml
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - "8554:8554"
    restart: always
  rtsp-server-speaker2:
    image: bluenviron/mediamtx:latest
    build:
      context: .
    volumes:
      - /Users/sebastiankravetz/Dev/Projects/AInterpreter_Hackathon/backend/whisper-live/speakertwo.yml:/mediamtx.yml
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - "8888:8888"
    restart: always