services:
  whisper-server1:
    build:
      context: .
      dockerfile: Dockerfile.srv1
    ports:
      - "9090:9090"  # Replace with the actual port your application is running on
    volumes:
      - .:/app  # Mounts the current directory to /app inside the container, adjust if needed
    restart: always  # Ensures the service restarts if it crashes
  whisper-server2:
    build:
      context: .
      dockerfile: Dockerfile.srv2
    ports:
      - "9091:9091"  # Replace with the actual port your application is running on
    volumes:
      - .:/app  # Mounts the current directory to /app inside the container, adjust if needed
    restart: always  # Ensures the service restarts if it crashes 
  rtsp-server-speaker1:
    image: bluenviron/mediamtx:latest
    build:
      context: .
    volumes:
      - ./speakerone.yml:/mediamtx.yml
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - "8554:8554"
    restart: always
  rtsp-server-speaker2:
    image: bluenviron/mediamtx:latest
    build:
      context: .
    volumes:
      - ./speakertwo.yml:/mediamtx.yml
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - "8888:8888"
    restart: always